### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by czhang23** [josephspurrier/golang-portable-windows#2]
I have been enjoying this windows version for some time.  I am wondering if you plan a Linux version.  Do you see a Linux version useful?

**Comment by josephspurrier** [comment]
I have no plans for Linux at this time. As far as I know, it's a little more difficult to create portable environments for Linux because the binaries have to be compiled for a specific distribution. I could create an environment for Ubuntu Desktop 14.04 LTS, but it wouldn't work on RedHat or other versions of Ubuntu.

**Comment by czhang23** [comment]
I do think the environment setup and connection between LiteIDE and Go is very valuable to have.  This provide an easy way to let different versions of Go co-exist on one box.  Regarding the binary version, maybe the easiest way is let the user to choose the binary they want to download and you may simply provide a few or none.  Even you only test one version on one OS, it is likely they will work for other versions and other OS with minor change by the User.

**Comment by josephspurrier** [comment]
It's not a bad idea, I did some reading and it looks like Go is portable: http://stackoverflow.com/questions/33872612/are-golang-binaries-portable. My primary development OS is Windows so I use my package all the time, but I don't write code in Linux (I just run my prod code from there) so it would difficult for me to testing extensively and give the project the justice it deserves.

Would you be interested in building a portable environment for Linux? I can certainly try to assist, but I can't take the lead on it.

**Comment by czhang23** [comment]
I am grad you like the idea.  Do you mind if I create a new project about Linux and port all or some of your windows scripts to Linux?  In reality, I am "copying" your ideas and design.  I guess it is easier this way so the two projects don't interfere each other.

**Comment by josephspurrier** [comment]
Absolutely, you can create a new project and port over anything you need. All I ask is you add a URL referencing this project at the bottom of your readme and you can use whatever license you want since the work will be yours: http://programmers.stackexchange.com/questions/316543/how-to-give-attribution-for-derivative-works-under-mit-when-the-work-is-a-port

**Comment by czhang23** [comment]
Will do.  Thanks.
